version: '3.8'

services:
  web:
    build: ./web
    env_file:  
      - ./.env  
    ports:
      - 4999:4999
    links:
      - db  


  db:
    build: ./db
    ports:
      - 27017:27017  
    env_file:  
      - ./.env  
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_ADMIN_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_ADMIN_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_ADMIN_USER  
      

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    links: 
      - db
    ports:
      - 8081:8081
    env_file:  
      - ./.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_DB_ADMIN_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_DB_ADMIN_PASSWORD
      ME_CONFIG_MONGODB_SERVER: db    